### ISSUE TITLE
Installation of qarpo locally

### ISSUE THREAD

**Issue by JobCollins** [ColfaxResearch/qarpo#1]
I am currently trying out the OpenVINO 2021.1 demos. On running one sample application locally (windows10) I get the error below

`ModuleNotFoundError: No module named 'qarpo'`

What I have tried is:

`pip install qarpo`

which gave

```
ERROR: Could not find a version that satisfies the requirement qarpo (from versions: none)
ERROR: No matching distribution found for qarpo
```

Could you please help me with installing this locally?

**Comment by davemaster** [comment]
Anybody? Same issue with me
